language: node_js
node_js:
- '7'
- '6'
after_script: cat ./coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: franz.becker@itemis.de
  api_key:
    secure: DIYRhDXoSKi7C4FRdGxOXzHx6TnMv4OZnEb5xHYaDJ7WO6vUd9ALS1azUDlHM2h56gj09UaxgbwRfASRA/vP+O9BkKVfkBodmaBLrSGI7A4jmL87OqQaQl2Zfa3mEVtjyo+WH3rbNJGbMTliQai4l7+ngiLiEKMfploP4gb9AA+n+sQzSu1QgpIaVHvOBDu9FPP4C+J6MyUVESvDYlELWPy1bbiOX3QK5z3TaSNNXqsbemdH/CVr7CCBJRwqaY+19fdoGClsLDDvMMCueJ8IVjM9pPTbTHuiSETQoiN8rpjZoFAySLJCBoE5468mUvStwEgTi00yAyUii6oDS0JUSgDW15U4Vg3AoUPKJMZ/QdeMgvR07QwfBVItofzIYrBsBDtsqlE/ceU00R4j0TAWbvvAMz+Jf5HSwsAILhcUeIxq/h1IZ5rWFIWhl/oxuJ0XG2cYj+lxMRPFpEsZCD+Sk575AL/NJ20oapXMLhwuzHmBXL4FisVGNnnztS6PR3uQFHoG91gkFtHgFZTyKsDKsatOKIKPdhXihBxtcnSUQh8RCinBrCi2Mxuygq5b/7HucYTdg6ns86zff/Nyjbu9a/fSpzk3xFmpZ/bCMrLesgT/OpcdjK1y6weWfzYsfztDp/wPT1Z2yambkSjFsTC9xySH0Mr0x4qgwENEqU0TX3I=
  on:
    tags: true
    repo: itemis/generator-xtext
    node: '6'
